#!/bin/sh

source "$( dirname ${0} )/env.sh"

set -x

helm upgrade --install che --namespace che \
--set global.ingressDomain=$(minikube ip).nip.io \
--set cheImage=eclipse/che-server:mvala \
--set global.cheWorkspaceNamespace=che \
${CHEDIR}/deploy/kubernetes/helm/che
