#!/bin/bash

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-build assembly

pushd "${CHEDIR}"/dockerfiles/che || exit
sh -x build.sh --organization:quay.io/mvala --prefix:che --name:server --tag:custom --dockerfile:Dockerfile
popd || exit
