#!/bin/bash

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  TARGETS=${*}
else
  TARGETS=.
fi

for TARGET in ${TARGETS}
do
  pushd "${CHEDIR}"/"${TARGET}" || exit
  mvn fmt:format license:format
  mvn install -DskipTests -T 1.5C
  popd || exit
done
