#!/bin/bash

set -e
set -x

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-build core
sh "${SCRIPT_DIR}"/che-build infrastructures
sh "${SCRIPT_DIR}"/che-build wsmaster
sh "${SCRIPT_DIR}"/che-orebuilddocker
sh "${SCRIPT_DIR}"/che-odeploycustom
