#!/bin/sh

set -x

SCRIPT_DIR=$( dirname "${0}" )

# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

#. "${SCRIPT_DIR}/che-cuploadimage"


NS=che
INTERNAL_REGISTRY=`oc registry info --internal=true`
CHE_IMAGE=${INTERNAL_REGISTRY}/${NS}/che-server
CHE_IMAGE_TAG=$( getCurrentBranch )

sed "s%{{CHE_IMAGE}}%${CHE_IMAGE}%g; s%{{CHE_IMAGE_TAG}}%${CHE_IMAGE_TAG}%g" "${SCRIPT_DIR}/org_v1_che_cr.yaml_template" > /tmp/che_cr.yaml

chectl server:start --platform=crc --installer=operator --che-operator-cr-patch-yaml=/tmp/che_cr.yaml
