#!/bin/bash

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  IMAGE=${1}
else
  IMAGE=quay.io/mvala/che-server:custom
fi

docker save "${IMAGE}" | ssh -i "$( minikube ssh-key )" -o StrictHostKeyChecking=no docker@"$( minikube ip )" "docker load"
