#!/bin/bash

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  TARGETS=${@}
fi

for TARGET in ${TARGETS}
do
  pushd "${CHEDIR}"/"${TARGET}" || exit
  mvn fmt:format
  mvn install -DskipTests -T 1.5C -Pnative
  popd || exit
done
