#!/bin/sh

set -e
set -u
set -x

source "$( dirname ${0} )/env.sh"

pushd ${CHEDIR}/assembly
mvn clean install
popd

pushd ${CHEDIR}/dockerfiles/che
eval $(minishift docker-env)
./build.sh --dockerfile:Dockerfile
popd
