#!/bin/sh

source "$( dirname ${0} )/env.sh"

pushd ${CHEDIR}/assembly
mvn clean install
popd

pushd ${CHEDIR}/dockerfiles/che
eval $(minikube docker-env)
sh build.sh --tag:mvala --dockerfile:Dockerfile
popd
