#!/bin/sh

set -x

SCRIPT_DIR=$( dirname "${0}" )

# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

CHEOP_IMAGE=quay.io/mvala/che-operator:gh20190-secureWsServicesTraefik

. "${SCRIPT_DIR}/che-deploy" minikube
