#!/bin/sh

if [ -z "${1}" ]; then
	MEMORY=8
else
	MEMORY=${1}
fi

minishift start --memory ${MEMORY}GB --disk-size=40GB --docker-opt userland-proxy=false

oc login -u system:admin --insecure-skip-tls-verify=true
oc adm policy add-cluster-role-to-user cluster-admin developer
oc delete project myproject
oc adm policy add-scc-to-group hostmount-anyuid system:serviceaccounts
oc login --username=developer --password=any --insecure-skip-tls-verify=true
oc delete project myproject

minishift ssh "sudo yum install chrony -y"
minishift ssh "sudo sed -i 's/makestep 1.0 3/makestep 1.0 -1/g' /etc/chrony.conf"
minishift ssh "sudo sed -i 's/\#allow/allow/g' /etc/chrony.conf"
minishift ssh "sudo systemctl enable chronyd"
minishift ssh "sudo systemctl start chronyd"
minishift ssh "sudo systemctl status chronyd"

oc login -u system:admin --insecure-skip-tls-verify=true
oc create namespace che
#. "$( dirname "${0}" )"/che-otls
