#!/bin/bash

set -x
set -e

DOMAIN="${DOMAIN:-*.$( minikube ip ).nip.io}"
CERT_DIR="/tmp/cert-${DOMAIN/\*/_}"

. "$( dirname "${0}" )/certgen.sh"

CERT_DIR="/tmp/cert-$( minikube ip ).nip.io"
mkdir -p "${CERT_DIR}"

pushd ${CERT_DIR}

if [ -d rootCA.crt ]; then
  echo "certificate already exist, just reuse it"
else
  certgen ${DOMAIN}
fi
cp rootCA.crt ca.crt
kubectl create namespace che
kubectl create secret tls che-tls --key=domain.key --cert=domain.crt -n che
kubectl create secret generic self-signed-certificate --from-file=ca.crt -n che

popd
