#!/bin/bash

set -e
set -u
set -x

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

pushd "${CHEDIR}"/assembly
mvn clean install
popd

pushd "${CHEDIR}"/dockerfiles/che
eval $(minishift docker-env)
./build.sh --dockerfile:Dockerfile --tag:mvala
popd
