#!/bin/bash

RELEASE_REPO_URL=https://api.github.com/repos/che-incubator/chectl/releases/latest
DOWNLOAD_ARTIFACT=chectl-linux
INSTALL_PATH=${HOME}/.local/opt/chectl-linux

#DOWNLOAD_URL=$( curl -sL ${RELEASE_REPO_URL}  | jq -r '.assets[].browser_download_url' | grep ${DOWNLOAD_ARTIFACT} )
DOWNLOAD_URL=$( curl -sL ${RELEASE_REPO_URL} | \
  jq -r ".assets[] | select(.name | contains(\"${DOWNLOAD_ARTIFACT}\")) | .browser_download_url" )

echo "${DOWNLOAD_URL}"
TIMESTAMP=$( date +%Y%m%d%H%M%S )
BACKUP_PATH="${INSTALL_PATH}"_bck"${TIMESTAMP}"
mv "${INSTALL_PATH}" "${BACKUP_PATH}" || true
wget -O "${INSTALL_PATH}" "${DOWNLOAD_URL}"
chmod +x "${INSTALL_PATH}"

#TODO: remove backup that is same as downloaded version
