#!/bin/bash

set -e

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-buildq "${*}"
sh "${SCRIPT_DIR}"/che-krebuilddocker
sh "${SCRIPT_DIR}"/che-krestartpod
sh "${SCRIPT_DIR}"/che-kurl
