#!/bin/sh

set -x

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

PORT=${1:-8000}

CHE_POD=$( getOcChePod )
echo Forwarding to pod "${CHE_POD}"
oc port-forward -n che "${CHE_POD}" "${PORT}":8000
