#!/bin/bash

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

NAMESPACE=che

kubectl apply -f "${CHEDIR}"/deploy/openshift/templates/monitoring/grafana-dashboards.yaml -n "${NAMESPACE}"
sed "s/{k8sip}/$(minikube ip)/g" "${SCRIPT_DIR}"/monitoring/prometheus_k8s.yaml | kubectl apply -n "${NAMESPACE}" -f -
sed "s/{k8sip}/$(minikube ip)/g" "${SCRIPT_DIR}"/monitoring/grafana_k8s.yaml | kubectl apply -n "${NAMESPACE}" -f -

echo
echo "http://grafana-$( minikube ip ).nip.io"
echo "http://prometheus-$( minikube ip ).nip.io"
