#!/bin/sh

SCRIPT_DIR=$( dirname "${0}" )

# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

INTERNAL_REGISTRY=`oc registry info --internal=true`
CHE_IMAGE=${INTERNAL_REGISTRY}/${CHE_NAMESPACE}/che-server
#CHE_IMAGE=${PRIVATE_DOCKERREGISTRY}/che-server
CHE_IMAGE_TAG=$( getCurrentBranch )

. "$( dirname "${0}" )"/che-cdeploy ${CHE_IMAGE} ${CHE_IMAGE_TAG}
