#!/bin/bash

. "$( dirname "${0}" )/env.sh"

OS_USER=${OS_USER:-$OPENSHIFT_REGISTRY_USER}
OS_PASS=${OS_PASS:-$OPENSHIFT_REGISTRY_PASS}

set +x
oc login --insecure-skip-tls-verify=true -u ${OS_USER} -p ${OS_PASS} ${OPENSHIFT_CLUSTER_URL}
