#!/bin/bash

set -e

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-buildwsmaster
sh "${SCRIPT_DIR}"/che-buildinfra
sh "${SCRIPT_DIR}"/che-krebuilddocker
sh "${SCRIPT_DIR}"/che-kdeploycustom
sh "${SCRIPT_DIR}"/che-krestartpod
