#!/bin/bash

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

set -x

TAG=$( getCurrentBranch )
# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  IMAGE=${1}
else
  IMAGE=quay.io/mvala/che-server:${TAG}
fi

. "$( dirname "${0}" )/che-cloginadmin"

oc create namespace ${CHE_NAMESPACE}

set -e
. "$( dirname "${0}" )/che-clogin"

REGISTRY=`oc registry info --public`
INTERNAL_REGISTRY=`oc registry info --internal=true`
IMAGE_NAME=${CHE_NAMESPACE}/che-server
NEWTAG=$( date +%s )
IMAGE=$IMAGE_NAME:$TAG

docker login --tls-verify=false -u $( oc whoami ) -p $( oc whoami -t ) $REGISTRY
docker tag quay.io/mvala/che-server:${TAG} $REGISTRY/$IMAGE
docker push --tls-verify=false $REGISTRY/$IMAGE
. "$( dirname "${0}" )/che-cloginadmin"
