#!/bin/sh

kubectl create secret generic che-tls --from-literal=ACME_EMAIL=mvala@redhat.com
kubectl create namespace cert-manager
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml --validate=false
