#!/bin/bash

set -e
set -x

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-buildwsmaster
sh "${SCRIPT_DIR}"/che-buildinfra
sh "${SCRIPT_DIR}"/che-orebuilddocker
sh "${SCRIPT_DIR}"/che-odeploycustom
