#!/bin/sh

# shellcheck source=./env.sh
. "$( dirname "${0}" )/env.sh"

set -x

helm upgrade --install che --namespace che \
--set global.ingressDomain=$(minikube ip).nip.io \
--set cheImage=quay.io/mvala/che-server:custom \
--set cheImagePullPolicy=IfNotPresent \
--set global.cheWorkspaceNamespace=che \
--set global.multiuser=true \
"${CHEDIR}"/deploy/kubernetes/helm/che
