#!/bin/sh

DATA=$( kubectl get secret che-identity-secret -n che -o json | jq '.data' )

USER=$( echo "${DATA}" | jq -r '.user' | base64 -d )
PASS=$( echo "${DATA}" | jq -r '.password' | base64 -d )

echo "username: ${USER}"
echo "password: ${PASS}"
