#!/bin/bash

function getKubeadminPassword() {
  cat ~/.crc/cache/*/kubeadmin-password
}

set -e

if [ -z "${1}" ]; then
  MEMORY=12
else
  MEMORY=${1}
fi

let "MEMORY = MEMORY * 1024"

set -x

sudo systemctl start libvirtd
sleep 1
crc start --memory ${MEMORY} --pull-secret-file ~/.crc/pull-secret
sleep 3
eval $( crc oc-env )
sleep 3
oc login -u kubeadmin -p $( getKubeadminPassword ) https://api.crc.testing:6443
oc delete project openshift-monitoring
oc delete project openshift-console
oc delete project openshift-console-operator

set +e


. "$( dirname "${0}" )"/che-clogin
oc create namespace che
. "$( dirname "${0}" )"/che-ctls

echo "import '/tmp/ca.crt' into your browser"
