#!/bin/bash

set -e

MEMORY=${1:-12}
let "MEMORY = MEMORY * 1024"

echo "starting crc with ${MEMORY} MiB memory ..."

set -x

sudo systemctl start libvirtd
sleep 1
crc start --memory ${MEMORY} --pull-secret-file ~/.crc/pull-secret
sleep 3
eval $( crc oc-env )
sleep 3
. "$( dirname "${0}" )"/che-cloginadmin

set +e


. "$( dirname "${0}" )"/che-clogin
. "$( dirname "${0}" )"/che-cregistryrole

echo "import '/tmp/ca.crt' into your browser"
