#!/bin/bash

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

TAG=$( getCurrentBranch )

sh "${SCRIPT_DIR}"/che-buildq assembly

pushd "${CHEDIR}"/dockerfiles/che || exit
sh -x build.sh --organization:${PRIVATE_DOCKERREGISTRY} --prefix:che --name:server --tag:${TAG} --dockerfile:Dockerfile
popd || exit

echo "docker push ${PRIVATE_DOCKERREGISTRY}/che-server:${TAG}"
