#!/bin/bash

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

set -x

TAG=$( getCurrentBranch )
# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  IMAGE=${1}
else
  IMAGE=${PRIVATE_DOCKERREGISTRY}/che-server:${TAG}
fi

docker save "${IMAGE}" | ssh -i "$( minikube ssh-key )" -o StrictHostKeyChecking=no docker@"$( minikube ip )" "docker load"
