#!/bin/sh

# shellcheck source=./env.sh
. "$( dirname "${0}" )/env.sh"

set -x

CHE_IMAGE_TAG=$( getCurrentBranch )
CHE_IMAGE=quay.io/mvala/che-server:${CHE_IMAGE_TAG}
#CHE_IMAGE=eclipse/che-server:nightly

helm dependencies update "${CHEDIR}"/deploy/kubernetes/helm/che

helm upgrade --install che --namespace che \
--set global.ingressDomain=$(minikube ip).nip.io \
--set cheImage=${CHE_IMAGE} \
--set cheImagePullPolicy=IfNotPresent \
--set global.cheWorkspaceNamespace=che \
"${CHEDIR}"/deploy/kubernetes/helm/che
