#!/bin/sh

# shellcheck source=./env.sh
. "$( dirname "${0}" )/env.sh"

CHE_IMAGE=${PRIVATE_DOCKERREGISTRY}/che-server:$( getCurrentBranch )

set -x

# generate certs when not already there
kc get secret self-signed-certificate -n ${CHE_NAMESPACE} || . "$( dirname "${0}" )/che-kcert"

kubectl create namespace ${CHE_NAMESPACE}

helm dependencies update "${CHEDIR}"/deploy/kubernetes/helm/che

helm upgrade --install che --namespace ${CHE_NAMESPACE} \
--set global.ingressDomain=$(minikube ip).nip.io \
--set cheImagePullPolicy=Never \
--set cheImage=${CHE_IMAGE} \
--set global.cheWorkspaceNamespace=che \
--set che.disableProbes=true \
--set che.logLevel=DEBUG \
-f "${CHEDIR}"/deploy/kubernetes/helm/che/values/tls.yaml \
"${CHEDIR}"/deploy/kubernetes/helm/che

. "$( dirname "${0}" )/che-kurl"
