#!/bin/bash

set -e

# shellcheck source=env.sh
SCRIPT_DIR=$( dirname "${0}" )
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-buildwsmaster
sh "${SCRIPT_DIR}"/che-krebuilddocker
sh "${SCRIPT_DIR}"/che-kdeploycustom
sh "${SCRIPT_DIR}"/che-krestartpod
