#!/bin/bash

set -e

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

sh "${SCRIPT_DIR}"/che-build "${*}"
sh "${SCRIPT_DIR}"/che-orebuilddocker
sh "${SCRIPT_DIR}"/che-orestartpod
sh "${SCRIPT_DIR}"/che-ourl
