#!/bin/sh

# shellcheck source=./env.sh
. "$( dirname "${0}" )/env.sh"

set -x

helm dependencies update "${CHEDIR}"/deploy/kubernetes/helm/che

helm upgrade --install che --namespace che \
--set global.ingressDomain=$(minikube ip).nip.io \
--set cheImagePullPolicy=IfNotPresent \
--set global.cheWorkspaceNamespace=che \
-f "${CHEDIR}"/deploy/kubernetes/helm/che/values/single-host-gateway.yaml \
-f "${CHEDIR}"/deploy/kubernetes/helm/che/values/tls.yaml \
"${CHEDIR}"/deploy/kubernetes/helm/che
