#!/bin/bash

set -x

SCRIPT_DIR=$( dirname "${0}" )

oc login -u kubeadmin -p $( "${SCRIPT_DIR}"/che-cpass ) https://api.crc.testing:6443
#oc login -u developer -p developer https://api.crc.testing:6443
