#!/bin/bash

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

set -e

URL=$( oc get routes -n ${CHE_NAMESPACE} | grep che- )
# shellcheck disable=SC2086
URL=$( echo ${URL} | cut -d' ' -f2 )

echo "https://${URL}"
echo "https://${URL}/swagger"
