#!/bin/bash

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  DIR=${1}
fi

pushd "${CHEDIR}"/"${DIR}" || exit
mvn fmt:format
mvn install -DskipTests -T 1.5C
popd || exit
