#!/bin/bash

set -x
set -e

SCRIPT_DIR=$( dirname "${0}" )
# shellcheck source=env.sh
. "${SCRIPT_DIR}/env.sh"

DOMAIN="${DOMAIN:-*.$( minikube ip ).nip.io}"
CERT_DIR="/tmp/cert-${DOMAIN/\*/_}"

. "$( dirname "${0}" )/certgen.sh"

CERT_DIR="/tmp/cert-$( minikube ip ).nip.io"
mkdir -p "${CERT_DIR}"

pushd ${CERT_DIR}

if [ -d rootCA.crt ]; then
  echo "certificate already exist, just reuse it"
else
  certgen ${DOMAIN}
fi
cp rootCA.crt ca.crt
kubectl create namespace che || true
kubectl create secret tls che-tls --key=domain.key --cert=domain.crt -n ${CHE_NAMESPACE}
kubectl create secret generic self-signed-certificate --from-file=ca.crt -n ${CHE_NAMESPACE}

popd
