#!/bin/bash

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

set -x

# shellcheck disable=SC2070
if [ -n "${1}" ]; then
  LOCAL_IMAGE=${1}
  TAG=$( echo ${LOCAL_IMAGE} | cut -d':' -f2 )
  IMAGE_NAME=$( echo ${LOCAL_IMAGE} | cut -d':' -f1 | cut -d'/' -f3 )
else
  TAG=$( getCurrentBranch )
  IMAGE_NAME=che-server
  LOCAL_IMAGE=${PRIVATE_DOCKERREGISTRY}/${IMAGE_NAME}:${TAG}
fi

. "$( dirname "${0}" )/che-cloginadmin"

oc create namespace ${CHE_NAMESPACE}

set -e
. "$( dirname "${0}" )/che-clogin"


REGISTRY=`oc registry info --public`
INTERNAL_REGISTRY=`oc registry info --internal=true`

REMOTE_IMAGE_NAME=${CHE_NAMESPACE}/${IMAGE_NAME}
NEWTAG=$( date +%s )
IMAGE=${REMOTE_IMAGE_NAME}:${TAG}
REMOTE_IMAGE=${REGISTRY}/${IMAGE}

docker login --tls-verify=false -u $( oc whoami ) -p $( oc whoami -t ) $REGISTRY
docker tag ${LOCAL_IMAGE} ${REMOTE_IMAGE}
docker push --tls-verify=false ${REMOTE_IMAGE}
. "$( dirname "${0}" )/che-cloginadmin"

echo
echo "original image ${LOCAL_IMAGE}"
echo "uploaded as ${REMOTE_IMAGE}"
