apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: che-che
  name: che-che
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: che-che
  namespace: che-che
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: che-che
  apiGroup: ""
