#!/bin/bash

set -e

. "$( dirname "${0}" )/env.sh"

IMAGE=${PRIVATE_DOCKERREGISTRY}/che-operator:$( getCurrentCheopBranch )

pushd "${CHEOPERATORDIR}" || exit
set -x

make generate
make manifests
make update-resources -s
make chectl-templ TARGET=/tmp/cheop-templates/che-operator

set +x
popd
