#!/bin/bash

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

IMAGE=${PRIVATE_DOCKERREGISTRY}/che-operator:$( getCurrentCheopBranch )
find . -not -path "./vendor/*" -name "*.go" -exec goimports -w {} \;

pushd "${CHEOPERATORDIR}" || exit
set -x
make fmt
make chectl-templ TARGET=/tmp/cheop-templates/che-operator

IMG=${IMAGE} make docker-build

kubectl scale deployment che-operator --replicas=0 -n ${CHE_NAMESPACE} || true
docker push ${IMAGE}
kubectl scale deployment che-operator --replicas=1 -n ${CHE_NAMESPACE} || true

# sh "$( dirname "${0}" )/che-cuploadimage" "${IMAGE}"
echo "${IMAGE}"
set +x
popd
