#!/bin/bash

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

IMAGE=${PRIVATE_DOCKERREGISTRY}/che-operator:$( getCurrentCheopBranch )

pushd "${CHEOPERATORDIR}" || exit
set -x
make chectl-templ TARGET=/tmp/cheop-templates/che-operator
IMG=${IMAGE} make docker-build
docker push ${IMAGE}
# docker push "${IMAGE}"
# sh "$( dirname "${0}" )/che-cuploadimage" "${IMAGE}"
echo "${IMAGE}"
set +x
popd
