#!/usr/bin/env sh

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

NAMESPACE=${1:-$CHE_NAMESPACE}

CURRENT_CONTEXT=$(kubectl config current-context)
kubectl config set-context "${CURRENT_CONTEXT}" --namespace="${NAMESPACE}"
echo "using [${NAMESPACE}] in [${CURRENT_CONTEXT}]"
